import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

const chenYuluoyan = localFont({
  src: './font/ChenYuluoyan-2.0-Thin.woff2',
  display: 'swap',
  variable: '--font-handwriting', 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-TW"
      className={`${geistSans.variable} ${geistMono.variable} ${chenYuluoyan.variable} h-full antialiased`}
    >
      <body className={`h-full flex items-center justify-center w-full bg-[#EAE5D8] p-2 sm:p-4 text-[#1E1C1A]`}>
      <div className="bg-[#FCFAEE] max-w-[440px] w-full h-[620px] rounded-2xl shadow-[0_8px_32px_rgba(30,28,26,0.08)] border-2 border-[#1E1C1A] flex flex-col justify-between overflow-hidden relative">
      {children}
        </div>
      </body>
    </html>
  );
}